### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by x554960766** [abuccts/ar-lucky-money-hunt#1]
File "restore.py", line 29, in <module>
    import cv2
ImportError: No module named cv2

**Comment by abuccts** [comment]
According to the [requirements](https://github.com/abuccts/ar-lucky-money-hunt#requirements), you should have `OpenCV` installed first.
You can refer to [Python Package Index](https://pypi.python.org/pypi/opencv-python/) or [OpenCV offical tutorials](http://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_setup/py_table_of_contents_setup/py_table_of_contents_setup.html) for opencv-python installation details.
